#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo "Starting pre-push hook..."

echo "Running TypeScript check..."
# Disabled to be able to push while updating to XState v5
# npx tsc --noEmit

echo ""
echo "Running Unit Tests"
# Disabled to be able to push while updating to XState v5
# npm run test -- --watchAll false --bail

echo ""
echo "All checks successful."
echo ""